jenkins:
  mode: EXCLUSIVE
  numExecutors: 0
  scmCheckoutRetryCount: 2
  disableRememberMe: true

  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://kubernetes.default"
        skipTlsVerify: true
        namespace: "kubesphere-devops-worker"
        credentialsId: "k8s-service-account"
        jenkinsUrl: "http://devops-jenkins.kubesphere-devops-system:80"
        jenkinsTunnel: "devops-jenkins-agent.kubesphere-devops-system:50000"
        containerCapStr: "2"
        connectTimeout: "60"
        readTimeout: "60"
        maxRequestsPerHostStr: "32"
        templates:
          - name: "base"
            namespace: "kubesphere-devops-worker"
            label: "base"
            nodeUsageMode: "NORMAL"
            idleMinutes: 0
            containers:
              - name: "base"
                image: "dockerhub.kubekey.local:5000/kubesphere/builder-base:v3.2.0-podman"
                command: "cat"
                args: ""
                ttyEnabled: true
                privileged: true
                resourceRequestCpu: "100m"
                resourceLimitCpu: "4000m"
                resourceRequestMemory: "100Mi"
                resourceLimitMemory: "8192Mi"
              - name: "jnlp"
                image: "dockerhub.kubekey.local:5000/jenkins/inbound-agent:4.10-2"
                args: "^${computer.jnlpmac} ^${computer.name}"
                resourceRequestCpu: "50m"
                resourceLimitCpu: "500m"
                resourceRequestMemory: "400Mi"
                resourceLimitMemory: "1536Mi"
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            volumes:
              - hostPathVolume:
                  hostPath: "/var/run/docker.sock"
                  mountPath: "/var/run/docker.sock"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_sonar_cache"
                  mountPath: "/root/.sonar/cache"
            yaml: |
              spec:
                affinity:
                  nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                        - key: node-role.kubernetes.io/worker
                          operator: In
                          values:
                          - ci
                tolerations:
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "NoSchedule"
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "PreferNoSchedule"
                containers:
                - name: "base"
                  resources:
                    requests:
                      ephemeral-storage: "1Gi"
                    limits:
                      ephemeral-storage: "10Gi"
                securityContext:
                  fsGroup: 1000

          - name: "nodejs"
            namespace: "kubesphere-devops-worker"
            label: "nodejs"
            nodeUsageMode: "EXCLUSIVE"
            idleMinutes: 0
            containers:
              - name: "nodejs"
                image: "dockerhub.kubekey.local:5000/jenkins-agent/builder-nodejs:v1.1-nodejs14"
                command: "cat"
                args: ""
                ttyEnabled: true
                privileged: true
                resourceRequestCpu: "100m"
                resourceLimitCpu: "4000m"
                resourceRequestMemory: "100Mi"
                resourceLimitMemory: "8192Mi"
              - name: "jnlp"
                image: "dockerhub.kubekey.local:5000/jenkins/inbound-agent:4.10-2"
                args: "^${computer.jnlpmac} ^${computer.name}"
                resourceRequestCpu: "50m"
                resourceLimitCpu: "500m"
                resourceRequestMemory: "400Mi"
                resourceLimitMemory: "1536Mi"
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            volumes:
              - hostPathVolume:
                  hostPath: "/var/run/docker.sock"
                  mountPath: "/var/run/docker.sock"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_nodejs_yarn_cache"
                  mountPath: "/root/.yarn"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_nodejs_npm_cache"
                  mountPath: "/root/.npm"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_sonar_cache"
                  mountPath: "/root/.sonar/cache"
            yaml: |
              spec:
                affinity:
                  nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                        - key: node-role.kubernetes.io/worker
                          operator: In
                          values:
                          - ci
                tolerations:
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "NoSchedule"
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "PreferNoSchedule"
                containers:
                - name: "nodejs"
                  resources:
                    requests:
                      ephemeral-storage: "1Gi"
                    limits:
                      ephemeral-storage: "10Gi"
                securityContext:
                  fsGroup: 1000

          - name: "maven"
            namespace: "kubesphere-devops-worker"
            label: "maven"
            nodeUsageMode: "EXCLUSIVE"
            idleMinutes: 0
            containers:
              - name: "maven"
                image: "dockerhub.kubekey.local:5000/jenkins-agent/builder-java:v1.1-java8"
                command: "cat"
                args: ""
                ttyEnabled: true
                privileged: true
                resourceRequestCpu: "100m"
                resourceLimitCpu: "4000m"
                resourceRequestMemory: "100Mi"
                resourceLimitMemory: "8192Mi"
              - name: "jnlp"
                image: "dockerhub.kubekey.local:5000/jenkins/inbound-agent:4.10-2"
                args: "^${computer.jnlpmac} ^${computer.name}"
                resourceRequestCpu: "50m"
                resourceLimitCpu: "500m"
                resourceRequestMemory: "400Mi"
                resourceLimitMemory: "1536Mi"
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            volumes:
              - hostPathVolume:
                  hostPath: "/var/run/docker.sock"
                  mountPath: "/var/run/docker.sock"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_maven_cache"
                  mountPath: "/root/.m2"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_sonar_cache"
                  mountPath: "/root/.sonar/cache"
            yaml: |
              spec:
                affinity:
                  nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                        - key: node-role.kubernetes.io/worker
                          operator: In
                          values:
                          - ci
                tolerations:
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "NoSchedule"
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "PreferNoSchedule"
                containers:
                - name: "maven"
                  resources:
                    requests:
                      ephemeral-storage: "1Gi"
                    limits:
                      ephemeral-storage: "10Gi"
                  volumeMounts:
                  - name: config-volume
                    mountPath: /opt/apache-maven-3.5.3/conf/settings.xml
                    subPath: settings.xml
                volumes:
                  - name: config-volume
                    configMap:
                      name: ks-devops-agent
                      items:
                      - key: MavenSetting
                        path: settings.xml
                securityContext:
                  fsGroup: 1000

          - name: "mavenjdk11"
            label: "jdk11 maven java"
            inheritFrom: "maven"
            containers:
              - name: "maven"
                image: "dockerhub.kubekey.local:5000/kubesphere/builder-maven:v3.2.0jdk11-podman"

          - name: "go"
            namespace: "kubesphere-devops-worker"
            label: "go"
            nodeUsageMode: "EXCLUSIVE"
            idleMinutes: 0
            containers:
              - name: "go"
                image: "dockerhub.kubekey.local:5000/kubesphere/builder-go:v3.2.0-podman"
                command: "cat"
                args: ""
                ttyEnabled: true
                privileged: true
                resourceRequestCpu: "100m"
                resourceLimitCpu: "4000m"
                resourceRequestMemory: "100Mi"
                resourceLimitMemory: "8192Mi"
              - name: "jnlp"
                image: "dockerhub.kubekey.local:5000/jenkins/inbound-agent:4.10-2"
                args: "^${computer.jnlpmac} ^${computer.name}"
                resourceRequestCpu: "50m"
                resourceLimitCpu: "500m"
                resourceRequestMemory: "400Mi"
                resourceLimitMemory: "1536Mi"
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            volumes:
              - hostPathVolume:
                  hostPath: "/var/run/docker.sock"
                  mountPath: "/var/run/docker.sock"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_go_cache"
                  mountPath: "/home/jenkins/go/pkg"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_sonar_cache"
                  mountPath: "/root/.sonar/cache"
            yaml: |
              spec:
                affinity:
                  nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                        - key: node-role.kubernetes.io/worker
                          operator: In
                          values:
                          - ci
                tolerations:
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "NoSchedule"
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "PreferNoSchedule"
                containers:
                - name: "go"
                  resources:
                    requests:
                      ephemeral-storage: "1Gi"
                    limits:
                      ephemeral-storage: "10Gi"
                securityContext:
                  fsGroup: 1000

          - name: "go16"
            label: "go16"
            inheritFrom: "go"
            containers:
              - name: "go"
                image: "dockerhub.kubekey.local:5000/kubesphere/builder-go:v3.2.0-1.16-podman"

          - name: "python"
            namespace: "kubesphere-devops-worker"
            label: "python"
            nodeUsageMode: "EXCLUSIVE"
            idleMinutes: 0
            containers:
              - name: "python"
                image: "dockerhub.kubekey.local:5000/kubesphere/builder-python:v3.2.0-podman"
                command: "cat"
                args: ""
                ttyEnabled: true
                privileged: true
                resourceRequestCpu: "100m"
                resourceLimitCpu: "4000m"
                resourceRequestMemory: "100Mi"
                resourceLimitMemory: "8192Mi"
              - name: "jnlp"
                image: "dockerhub.kubekey.local:5000/jenkins/inbound-agent:4.10-2"
                args: "^${computer.jnlpmac} ^${computer.name}"
                resourceRequestCpu: "50m"
                resourceLimitCpu: "500m"
                resourceRequestMemory: "400Mi"
                resourceLimitMemory: "1536Mi"
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            volumes:
              - hostPathVolume:
                  hostPath: "/var/run/docker.sock"
                  mountPath: "/var/run/docker.sock"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_python_pip_cache"
                  mountPath: "/root/.cache/pip"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_python_pipenv_cache"
                  mountPath: "/root/.local/share/virtualenvs"
              - hostPathVolume:
                  hostPath: "/var/data/jenkins_sonar_cache"
                  mountPath: "/root/.sonar/cache"
            yaml: |
              spec:
                affinity:
                  nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                        - key: node-role.kubernetes.io/worker
                          operator: In
                          values:
                          - ci
                tolerations:
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "NoSchedule"
                - key: "node.kubernetes.io/ci"
                  operator: "Exists"
                  effect: "PreferNoSchedule"
                containers:
                - name: "python"
                  resources:
                    requests:
                      ephemeral-storage: "1Gi"
                    limits:
                      ephemeral-storage: "10Gi"
                securityContext:
                  fsGroup: 1000

  securityRealm:
    ldap:
      configurations:
        - displayNameAttributeName: "uid"
          mailAddressAttributeName: "mail"
          inhibitInferRootDN: false
          managerDN: "cn=admin,dc=kubesphere,dc=io"
          managerPasswordSecret: "admin"
          rootDN: "dc=kubesphere,dc=io"
          userSearchBase: "ou=Users"
          userSearch: "(&(objectClass=inetOrgPerson)(|(uid={0})(mail={0})))"
          groupSearchBase: "ou=Groups"
          groupSearchFilter: "(&(objectClass=posixGroup)(cn={0}))"
          server: "ldap://openldap.kubesphere-system.svc:389"
      disableMailAddressResolver: false
      disableRolePrefixing: true


unclassified:
  location:
    url: "http://jenkins.devops.kubesphere.local"
  kubespheretokenauthglobalconfiguration:
    cacheConfiguration:
      size: 20
      ttl: 300
    enabled: true
    server: "http://devops-apiserver.kubesphere-devops-system:9090/"
  eventDispatcher:
    receiver: "http://devops-apiserver.kubesphere-devops-system:9090/v1alpha3/webhooks/jenkins"
  gitLabServers:
    servers:
      - name: "https://gitlab.cpirhzl.com"
        serverUrl: "https://gitlab.cpirhzl.com"
