apply plugin: 'maven-publish'

def publishProperties = new Properties()
publishProperties.load(new FileInputStream(rootProject.file("publish.properties")))

afterEvaluate {
    publishing {
        publications {
            if (project.plugins.findPlugin('java') != null && project.plugins.findPlugin('java-library') != null) {
                mavenPublication(MavenPublication) {
                    from components.java

                    // 添加源码Jar到出版物
                    artifact(tasks.named('sourcesJar')) {
                        classifier 'sources'
                    }

                    // 增加版本映射，如果不加，会不知道pom中的版本是什么，这里设置为自动解析
                    versionMapping {
                        usage('java-api') {
                            fromResolutionResult()
                        }
                        usage('java-runtime') {
                            fromResolutionResult()
                        }
                    }
                }
            } else if (project.plugins.findPlugin('java-platform') != null) {
                mavenJava(MavenPublication) {
                    from components.javaPlatform
                }
            }
        }
        repositories {
            maven {
                url = publishProperties.getProperty("maven.publish.release.url")
                credentials {
                    username = publishProperties.getProperty("maven.publish.release.username")
                    password = publishProperties.getProperty("maven.publish.release.password")
                }
            }
            maven {
                url = publishProperties.getProperty("maven.publish.snapshot.url")
                credentials {
                    username = publishProperties.getProperty("maven.publish.snapshot.username")
                    password = publishProperties.get("maven.publish.snapshot.password")
                }
            }
        }
    }
}
