version: '2'

services:
  zk:
    image: zookeeper
    restart: unless-stopped
    hostname: zk
    ports:
      - "2181:2181"
    container_name: zookeeper

  kfk:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zk
    container_name: kafka
