version: "3.7"
services:
  minio:
    image: "minio/minio:${MINIO_IMAGE_TAG}"
    ports:
      - "${MINIO_PORT_API}:9000"
      - "${MINIO_PORT_CONSOLE}:9001"
    restart: always
    environment:
      # 在变量中配置账号密码
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ".${MINIO_VOLUME_DATA_PATH}:/data"
    command: server --console-address ":${MINIO_PORT_CONSOLE}" /data
    healthcheck:
      test:
        - "cmd"
        - "curl"
        - "-f"
        - "http://localhost:9000/minio/health/live"
      interval: 30s
      timeout: 20s
      retries: 3
