version: '3'
services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql-lable
    volumes:
      - ./data/mysql/datadir:/var/lib/mysql
      - ./data/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./data/mysql/sql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=miemiemie"
      - "MYSQL_DATABASE=miemiemie"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"